install.packages("sf")
install.packages("leaflet")
install.packages("tm")
install.packages("text2vec")
install.packages("LDAvis")
install.packages("caret", dependencies = c("Depends", "Suggests"))
install.packages("igraph")
install.packages("networkVis")
install.packages("shiny")
install.packages("flexdashboard")
install.packages("shinydashboard")
